=== project-chip/connectedhomeip/data_model/xsd/devicetype.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:include schemaLocation="types.xsd" />
  <xs:include schemaLocation="constraint.xsd" />
  <xs:include schemaLocation="conformance.xsd" />

  <xs:element name="deviceType" type="DeviceTypeType" />

  <xs:complexType name="ConditionType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="summary" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ConditionsType">
    <xs:sequence>
      <xs:element name="condition" type="ConditionType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="FeatureRequirementType">
    <xs:sequence>
      <xs:element name="quality" type="QualityType" minOccurs="0" maxOccurs="1" />
      <xs:element name="constraint" type="ConstraintType" minOccurs="0" maxOccurs="1" />
      <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="FeaturesRequirementType">
    <xs:sequence>
      <xs:element name="feature" type="FeatureRequirementType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AttributeRequirementType">
    <xs:sequence>
      <xs:element name="quality" type="QualityType" minOccurs="0" maxOccurs="1" />
      <xs:element name="constraint" type="ConstraintType" minOccurs="0" maxOccurs="1" />
      <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="AttributesRequirementType">
    <xs:sequence>
      <xs:element name="attribute" type="AttributeRequirementType" minOccurs="1"
        maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CommandRequirementType">
    <xs:sequence>
      <xs:element name="quality" type="QualityType" minOccurs="0" maxOccurs="1" />
      <xs:element name="constraint" type="ConstraintType" minOccurs="0" maxOccurs="1" />
      <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="CommandsRequirementType">
    <xs:sequence>
      <xs:element name="command" type="CommandRequirementType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventRequirementType">
    <xs:sequence>
      <xs:element name="quality" type="QualityType" minOccurs="0" maxOccurs="1" />
      <xs:element name="constraint" type="ConstraintType" minOccurs="0" maxOccurs="1" />
      <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="EventsRequirementType">
    <xs:sequence>
      <xs:element name="event" type="EventRequirementType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ClusterRequirementType">
    <xs:sequence>
      <xs:element name="quality" type="QualityType" minOccurs="0" maxOccurs="1" />
      <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
      <xs:element name="features" type="FeaturesRequirementType" minOccurs="0" maxOccurs="1" />
      <xs:element name="attributes" type="AttributesRequirementType" minOccurs="0" maxOccurs="1" />
      <xs:element name="commands" type="CommandsRequirementType" minOccurs="0" maxOccurs="1" />
      <xs:element name="events" type="EventsRequirementType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="side" type="xs:string" use="optional" />

  </xs:complexType>

  <xs:complexType name="ClusterRequirementsType">
    <xs:sequence>
      <xs:element name="cluster" type="ClusterRequirementType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConditionRequirementType">
    <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ConditionRequirementsType">
    <xs:sequence>
      <xs:element name="deviceType" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="conditionRequirement" type="ConditionRequirementType" minOccurs="1"
              maxOccurs="unbounded" />
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ComposedDeviceTypesType">
    <xs:sequence>
      <xs:element name="deviceType" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="ConformanceSetGroup" minOccurs="0" maxOccurs="1" />
            <xs:element name="clusterRequirements" type="ClusterRequirementsType" minOccurs="0"
              maxOccurs="1" />
          </xs:sequence>
          <xs:attribute name="deviceTypeId" type="xs:string" use="required" />
          <xs:attribute name="deviceTypeName" type="xs:string" use="required" />


        </xs:complexType>
      </xs:element>
      <xs:element name="cluster" type="ClusterRequirementType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DeviceTypeType">
    <xs:sequence>
      <xs:element name="revisionHistory" type="RevisionHistoryType" minOccurs="1" maxOccurs="1" />
      <xs:element name="classification" type="ClassificationType" minOccurs="0" maxOccurs="1" />
      <xs:element name="conditions" type="ConditionsType" minOccurs="0" maxOccurs="1" />
      <xs:element name="conditionRequirements" type="ConditionRequirementsType" minOccurs="0"
        maxOccurs="1" />
      <xs:element name="clusters" type="ClusterRequirementsType" minOccurs="0" maxOccurs="1" />
      <xs:element name="composedDeviceTypes" type="ComposedDeviceTypesType" minOccurs="0"
        maxOccurs="2" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="optional" />
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="revision" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="ClassificationType">
    <xs:attribute name="class" type="xs:string" use="required" />
    <xs:attribute name="scope" type="xs:string" use="required" />
    <xs:attribute name="superset" type="xs:string" use="optional" />
  </xs:complexType>

</xs:schema>

=== project-chip/connectedhomeip/data_model/1.7/device_types/PressureSensor.xml
<?xml version="1.0"?>
<!--
Copyright (C) Connectivity Standards Alliance (2026). All rights reserved.
The information within this document is the property of the Connectivity
Standards Alliance and its use and disclosure are restricted, except as
expressly set forth herein.

Connectivity Standards Alliance hereby grants you a fully-paid, non-exclusive,
nontransferable, worldwide, limited and revocable license (without the right to
sublicense), under Connectivity Standards Alliance's applicable copyright
rights, to view, download, save, reproduce and use the document solely for your
own internal purposes and in accordance with the terms of the license set forth
herein. This license does not authorize you to, and you expressly warrant that
you shall not: (a) permit others (outside your organization) to use this
document; (b) post or publish this document; (c) modify, adapt, translate, or
otherwise change this document in any manner or create any derivative work
based on this document; (d) remove or modify any notice or label on this
document, including this Copyright Notice, License and Disclaimer. The
Connectivity Standards Alliance does not grant you any license hereunder other
than as expressly stated herein.

Elements of this document may be subject to third party intellectual property
rights, including without limitation, patent, copyright or trademark rights,
and any such third party may or may not be a member of the Connectivity
Standards Alliance. Connectivity Standards Alliance members grant other
Connectivity Standards Alliance members certain intellectual property rights as
set forth in the Connectivity Standards Alliance IPR Policy. Connectivity
Standards Alliance members do not grant you any rights under this license. The
Connectivity Standards Alliance is not responsible for, and shall not be held
responsible in any manner for, identifying or failing to identify any or all
such third party intellectual property rights. Please visit www.csa-iot.org for
more information on how to become a member of the Connectivity Standards
Alliance.

This document and the information contained herein are provided on an “AS IS”
basis and the Connectivity Standards Alliance DISCLAIMS ALL WARRANTIES EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO (A) ANY WARRANTY THAT THE USE OF THE
INFORMATION HEREIN WILL NOT INFRINGE ANY RIGHTS OF THIRD PARTIES (INCLUDING
WITHOUT LIMITATION ANY INTELLECTUAL PROPERTY RIGHTS INCLUDING PATENT, COPYRIGHT
OR TRADEMARK RIGHTS); OR (B) ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE, TITLE OR NONINFRINGEMENT. IN NO EVENT WILL THE
CONNECTIVITY STANDARDS ALLIANCE BE LIABLE FOR ANY LOSS OF PROFITS, LOSS OF
BUSINESS, LOSS OF USE OF DATA, INTERRUPTION OF BUSINESS, OR FOR ANY OTHER
DIRECT, INDIRECT, SPECIAL OR EXEMPLARY, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL
DAMAGES OF ANY KIND, IN CONTRACT OR IN TORT, IN CONNECTION WITH THIS DOCUMENT
OR THE INFORMATION CONTAINED HEREIN, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
LOSS OR DAMAGE.

All company, brand and product names in this document may be trademarks that
are the sole property of their respective owners.

This notice and disclaimer must be included on all copies of this document.

Connectivity Standards Alliance
508 Second Street, Suite 206
Davis, CA 95616, USA

:xrefstyle: basic
-->
<deviceType xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="types types.xsd devicetype devicetype.xsd" id="0x0305" name="Pressure Sensor" revision="3">
  <revisionHistory>
    <revision revision="1" summary="Initial Zigbee 3.0 revision"/>
    <revision revision="2" summary="New data model format and notation"/>
    <revision revision="3" summary="Removed Zigbee related elements"/>
  </revisionHistory>
  <classification class="simple" scope="endpoint"/>
  <clusters>
    <cluster id="0x0003" name="Identify" side="server">
      <mandatoryConform/>
    </cluster>
    <cluster id="0x0403" name="Pressure Measurement" side="server">
      <mandatoryConform/>
    </cluster>
  </clusters>
</deviceType>
