=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/silabs/schema/zcl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2008,2020 Silicon Labs.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
    <xs:annotation>
      <xs:documentation>This schema describes the format of the XML files, that describe the ZCL specification.
It does not describe over-the-air format of the packet.

Copyright 2012, Silicon Laboratories Inc.</xs:documentation></xs:annotation>
    <xs:element name="cli">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="group" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="configurator">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="callback" />
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="deviceType" />
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element minOccurs="0" ref="global" />
          <xs:element minOccurs="0" maxOccurs="unbounded" ref="domain" />
        </xs:choice>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="atomic" />
          <xs:element ref="bitmap" />
          <xs:element ref="cluster" />
          <xs:element ref="clusterExtension" />
          <xs:element ref="enum" />
          <xs:element ref="struct" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="domain" />
        <xs:element ref="typeName" />
        <xs:element ref="zigbeeType" />
        <xs:element ref="profileId" />
        <xs:element ref="deviceId" />
        <xs:element minOccurs="0" ref="channels" />
        <xs:element ref="clusters" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typeName" type="xs:string" />
  <xs:element name="zigbeeType">
    <xs:complexType mixed="true">
      <xs:attribute name="editable" use="optional" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="profileId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="deviceId">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="editable" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="channels">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="channel" />
      </xs:sequence>
      <xs:attribute name="editable" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="channel">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="11"></xs:minInclusive>
        <xs:maxInclusive value="26"></xs:maxInclusive>
        <xs:whiteSpace value="collapse"></xs:whiteSpace>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="clusters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="include" />
      </xs:sequence>
      <xs:attribute name="lockOthers" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="include">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="requireAttribute" />
        <xs:element ref="requireCommand" />
      </xs:choice>
      <xs:attribute name="client" use="required" type="xs:boolean" />
      <xs:attribute name="clientLocked" use="required" type="xs:boolean" />
      <xs:attribute name="cluster" />
      <xs:attribute name="server" use="required" type="xs:boolean" />
      <xs:attribute name="serverLocked" use="required" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="requireAttribute" type="zclAttributeDefine" />
  <xs:element name="requireCommand" type="zclCommandName" />
  <xs:element name="global">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="command" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="atomic">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="type" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="description" use="required" type="xs:string" />
      <xs:attribute name="size" type="xs:integer" />
      <xs:attribute name="discrete" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="bitmap">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="field" />
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="type" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:attribute name="mask" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="introducedIn" type="zclSpecVersion" />
    </xs:complexType>
  </xs:element>
  <xs:element name="globalAttribute">
    <xs:complexType>
      <xs:attribute name="side" use="required" type="zclSideWithEither" />
      <xs:attribute name="code" use="required" type="xs:string" />
      <xs:attribute name="value" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="domain" />
        <xs:element ref="description" />
        <xs:element ref="code" />
        <xs:element ref="define" />
        <xs:element ref="client" />
        <xs:element ref="server" />
        <xs:element minOccurs="0" ref="generateCmdHandlers" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="globalAttribute" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="command" />
      </xs:sequence>
      <xs:attribute name="introducedIn" type="xs:string" />
      <xs:attribute name="manufacturerCode" type="zclCode" />
      <xs:attribute name="singleton" type="xs:boolean" />
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="zclCode" />
  <xs:element name="define" type="xs:string" />
  <xs:element name="client">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean" />
          <xs:attribute name="tick" use="required" type="xs:boolean" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="server">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:boolean">
          <xs:attribute name="init" use="required" type="xs:boolean" />
          <xs:attribute name="tick" use="required" type="xs:boolean" />
          <xs:attribute name="tickFrequency" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="generateCmdHandlers" type="xs:boolean" />
  <xs:element name="clusterExtension">
    <xs:complexType>
    	<xs:sequence>
    		<xs:element minOccurs="0" maxOccurs="unbounded"
    			ref="attribute" />
    		<xs:element minOccurs="0" maxOccurs="unbounded"
    			ref="command" />
    	</xs:sequence>
    	<xs:attribute name="code" use="required" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="enum">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="item" />
      </xs:sequence>
      <xs:attribute name="description" />
      <xs:attribute name="name" use="required" type="xs:string" />
      <xs:attribute name="type" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="struct">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="item" />
      </xs:sequence>
      <xs:attribute name="length" type="xs:integer" />
      <xs:attribute name="name" use="required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="callback">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="function" />
      </xs:sequence>
      <xs:attribute name="postfix" type="xs:string" />
      <xs:attribute name="prefix" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="function">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="description" />
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
        <xs:element minOccurs="0" ref="codeForStub" />
      </xs:sequence>
      <xs:attribute name="category" type="xs:string" />
      <xs:attribute name="cluster" />
      <xs:attribute name="consumed" type="xs:boolean" />
      <xs:attribute name="id" use="required" type="xs:string" />
      <xs:attribute name="name" use="required" />
      <xs:attribute name="platformType" type="xs:string" />
      <xs:attribute name="returnType" use="required" type="xs:string" />
      <xs:attribute name="side" type="zclSide" />
      <xs:attribute name="stackMacro" />
    </xs:complexType>
  </xs:element>
  <xs:element name="codeForStub" type="xs:string" />
  <xs:element name="name" type="xs:string" />
  <xs:element name="domain">
    <xs:complexType mixed="true">
    	<xs:sequence>
    		<xs:element minOccurs="0" maxOccurs="unbounded" ref="older" />
    	</xs:sequence>
    	<xs:attribute name="dependsOn" type="zclSpecVersion" />
    	<xs:attribute name="name" />
    	<xs:attribute name="spec" type="zclSpecVersion" />
    	<xs:attribute name="certifiable" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="older">
    <xs:complexType>
    	<xs:attribute name="dependsOn" use="optional" type="xs:string" />
    	<xs:attribute name="spec" use="required" type="xs:string" />
    	<xs:attribute name="certifiable" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="command">
    <xs:complexType>
    	<xs:sequence>
    		<xs:element ref="description" />
    		<xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
    	</xs:sequence>
    	<xs:attribute name="cli" />
    	<xs:attribute name="cliFunctionName" type="xs:string" />
    	<xs:attribute name="code" type="xs:string" />
    	<xs:attribute name="disableDefaultResponse" type="xs:boolean" />
    	<xs:attribute name="functionName" type="xs:string" />
    	<xs:attribute name="group" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="noDefaultImplementation" type="xs:boolean"></xs:attribute>
    	<xs:attribute name="manufacturerCode" type="xs:string" />
    	<xs:attribute name="name" type="xs:string" />
    	<xs:attribute name="optional" type="xs:boolean" />
    	<xs:attribute name="source" type="xs:string" />
    	<xs:attribute name="restriction" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="name" use="required" type="xs:string" />
    	<xs:attribute name="type" type="xs:string" />
    	<xs:attribute name="value" type="xs:string" />
    	<xs:attribute name="array" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="attribute">
    <xs:complexType mixed="true">
    	<xs:attribute name="code" use="required" type="zclCode" />
    	<xs:attribute name="default" />
    	<xs:attribute name="define" use="required"
    		type="zclAttributeDefine" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="length" type="xs:integer" />
    	<xs:attribute name="manufacturerCode" type="zclCode" />
    	<xs:attribute name="max" type="xs:anySimpleType" />
    	<xs:attribute name="min" type="xs:anySimpleType" />
    	<xs:attribute name="optional" use="required" type="xs:boolean" />
    	<xs:attribute name="side" use="required" type="zclSide" />
    	<xs:attribute name="type" use="required" type="xs:string" />
    	<xs:attribute name="readable" type="xs:boolean" />
    	<xs:attribute name="writable" type="xs:boolean" />
    	<xs:attribute name="reportable" type="xs:boolean" />
    	<xs:attribute name="array" type="xs:boolean"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="arg" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="arg">
        <xs:annotation>
        	<xs:documentation>An optional attribute, that specifies the length argument.

This is used in cases where a length argument is preceding the actual array.

In those cases, an array becomes a known length, and you can have variable length arguments after it.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        <xs:attribute name="arrayLength" type="xs:boolean" />
    	<xs:attribute name="array" type="xs:boolean" />
    	<xs:attribute name="default" type="xs:string" />
    	<xs:attribute name="description" type="xs:string" />
    	<xs:attribute name="introducedIn" type="zclSpecVersion" />
    	<xs:attribute name="removedIn" type="zclSpecVersion"></xs:attribute>
    	<xs:attribute name="name" use="required" />
    	<xs:attribute name="type" use="required" />
    	<xs:attribute name="length" type="xs:int"></xs:attribute>
    	<xs:attribute name="presentIf" type="xs:string" />
    	<xs:attribute name="optional" type="xs:integer" />
    	<xs:attribute name="countArg" type="xs:string" use="optional"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="zclAttributeDefine">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclCommandName">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSpecVersion">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclCode">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSide">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"></xs:enumeration>
      <xs:enumeration value="server"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="zclSideWithEither">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"></xs:enumeration>
      <xs:enumeration value="server"></xs:enumeration>
      <xs:enumeration value="either"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="mapping">
    <xs:complexType>
      <xs:attribute name="code" type="xs:string" />
      <xs:attribute name="translation" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="map">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="mapping" />
        </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/diagnostic-logs-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2021-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/service_device_management/DiagnosticLogsCluster.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ attribute=ambient-context-sensor,ambientsensing,cameras,cameras-image-rotation,groupcast,hrap-pdc,hrap-tbrd,hvac-thermostat-events,hvac-thermostat-suggestions,improved-capabilities-tcr,partitioned-crl,security-sensor-events-tcr,tcr-smokeco-unmounted-state,temperature-alarm,thread-commissioning 
Git: 0.7-recirc-1.7-310-gce68ecc95
Alchemy: v1.7.10
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="CHIP" spec="chip-0.7" dependsOn="zcl-1.0-07-5123-03" certifiable="true"/>
  <enum name="IntentEnum" type="enum8">
    <cluster code="0x0032"/>
    <item name="EndUserSupport" value="0x0"/>
    <item name="NetworkDiag" value="0x1"/>
    <item name="CrashLogs" value="0x2"/>
  </enum>

  <enum name="StatusEnum" type="enum8">
    <cluster code="0x0032"/>
    <item name="Success" value="0x0"/>
    <item name="Exhausted" value="0x1"/>
    <item name="NoLogs" value="0x2"/>
    <item name="Busy" value="0x3"/>
    <item name="Denied" value="0x4"/>
  </enum>

  <enum name="TransferProtocolEnum" type="enum8">
    <cluster code="0x0032"/>
    <item name="ResponsePayload" value="0x0"/>
    <item name="BDX" value="0x1"/>
  </enum>

  <cluster>
    <name>Diagnostic Logs</name>
    <domain>General</domain>
    <description>The cluster provides commands for retrieving unstructured diagnostic logs from a Node that may be used to aid in diagnostics.</description>
    <code>0x0032</code>
    <define>DIAGNOSTIC_LOGS_CLUSTER</define>
    <client tick="false" init="false">true</client>
    <server tick="false" init="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="1"/>
    <command source="client" code="0x00" name="RetrieveLogsRequest" response="RetrieveLogsResponse" cli="chip logs retrieve">
      <description>Reception of this command starts the process of retrieving diagnostic logs from a Node.</description>
      <arg fieldId="0" name="Intent" type="IntentEnum" max="0x02"/>
      <arg fieldId="1" name="RequestedProtocol" type="TransferProtocolEnum" max="0x01"/>
      <arg fieldId="2" name="TransferFileDesignator" type="char_string" length="32" optional="true"/>
      <mandatoryConform/>
    </command>

    <command source="server" code="0x01" name="RetrieveLogsResponse" cli="chip logs response" disableDefaultResponse="true">
      <description>This SHALL be generated as a response to the RetrieveLogsRequest.</description>
      <arg fieldId="0" name="Status" type="StatusEnum" max="0x04"/>
      <arg fieldId="1" name="LogContent" type="long_octet_string" length="1024"/>
      <arg fieldId="2" name="UTCTimeStamp" type="epoch_us" optional="true"/>
      <arg fieldId="3" name="TimeSinceBoot" type="systime_us" optional="true"/>
      <mandatoryConform/>
    </command>

  </cluster>
</configurator>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/mode-select-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2021-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/app_clusters/ModeSelect.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ 
Git: 0.9-1.7-winter2027-349-g23eb5a49a
Alchemy: v1.7.12
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="CHIP"/>
  <struct name="SemanticTagStruct">
    <cluster code="0x0050"/>
    <item fieldId="0" name="MfgCode" type="vendor_id"/>
    <item fieldId="1" name="Value" type="enum16"/>
  </struct>

  <struct name="ModeOptionStruct">
    <cluster code="0x0050"/>
    <item fieldId="0" name="Label" type="char_string" length="64"/>
    <item fieldId="1" name="Mode" type="int8u"/>
    <item fieldId="2" name="SemanticTags" type="SemanticTagStruct" array="true" length="64"/>
  </struct>

  <cluster>
    <domain>General</domain>
    <name>Mode Select</name>
    <code>0x0050</code>
    <define>MODE_SELECT_CLUSTER</define>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute side="either" code="0xFFFD" value="2"/>
    <features>
      <feature bit="0" code="DEPONOFF" name="OnOff" summary="Dependency with the OnOff cluster">
        <optionalConform/>
      </feature>
    </features>
    <description>Attributes and commands for selecting a mode from a list of supported options.</description>
    <!-- Base data types -->
    <attribute side="server" code="0x0000" name="Description" define="MODE_DESCRIPTION" type="char_string" length="64"/>
    <attribute side="server" code="0x0001" name="StandardNamespace" define="STANDARD_NAMESPACE" type="enum16" isNullable="true"/>
    <attribute side="server" code="0x0002" name="SupportedModes" define="SUPPORTED_MODES" type="array" entryType="ModeOptionStruct" length="255"/>
    <attribute side="server" code="0x0003" name="CurrentMode" define="CURRENT_MODE" type="int8u"/>
    <attribute side="server" code="0x0004" name="StartUpMode" define="START_UP_MODE" type="int8u" writable="true" isNullable="true" optional="true">
      <optionalConform/>
    </attribute>
    <attribute side="server" code="0x0005" name="OnMode" define="ON_MODE" type="int8u" writable="true" isNullable="true" optional="true">
      <mandatoryConform>
        <feature name="DEPONOFF"/>
      </mandatoryConform>
    </attribute>
    <!-- Test Commands -->
    <command source="client" code="0x00" name="ChangeToMode">
      <description>On receipt of this command, if the NewMode field indicates a valid mode transition within the supported list, the server SHALL set the CurrentMode attribute to the NewMode value, otherwise, the server SHALL respond with an INVALID_COMMAND status response.</description>
      <arg fieldId="0" name="NewMode" type="int8u"/>
      <mandatoryConform/>
    </command>

  </cluster>
</configurator>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/binding-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2020-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/data_model/Binding-Cluster.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ attribute=ambient-context-sensor,ambientsensing,cameras,cameras-image-rotation,groupcast,hrap-pdc,hrap-tbrd,hvac-thermostat-events,hvac-thermostat-suggestions,improved-capabilities-tcr,partitioned-crl,security-sensor-events-tcr,tcr-smokeco-unmounted-state,temperature-alarm,thread-commissioning 
Git: 0.7-recirc-1.7-310-gce68ecc95
Alchemy: v1.7.10
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="CHIP"/>
  <struct name="TargetStruct" isFabricScoped="true">
    <cluster code="0x001e"/>
    <item fieldId="1" name="Node" type="node_id" optional="true"/>
    <item fieldId="2" name="Group" type="group_id" optional="true" min="1"/>
    <item fieldId="3" name="Endpoint" type="endpoint_no" optional="true"/>
    <item fieldId="4" name="Cluster" type="cluster_id" optional="true"/>
  </struct>

  <cluster>
    <domain>General</domain>
    <name>Binding</name>
    <code>0x001e</code>
    <define>BINDING_CLUSTER</define>
    <description>The Binding Cluster is meant to replace the support from the Zigbee Device Object (ZDO) for supporting the binding table.</description>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="1"/>
    <attribute side="server" code="0x0000" name="Binding" define="BINDING_LIST" type="array" entryType="TargetStruct" writable="true">
      <access op="write" role="manage"/>
      <mandatoryConform/>
    </attribute>
  </cluster>
</configurator>

=== project-chip/connectedhomeip/src/app/zap-templates/zcl/data-model/chip/soil-measurement-cluster.xml
<?xml version="1.0"?>
<!--
Copyright (c) 2025-2026 Project CHIP Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<!--
XML generated by Alchemy; DO NOT EDIT.
Source: src/app_clusters/SoilMeasurement.adoc
Parameters: zap ignore-errored provisional-policy=loose sdkRoot=./connectedhomeip/ specRoot=./connectedhomeip-spec/ attribute=in-progress 
Git: 0.9-1.7-winter2027-349-g23eb5a49a
Alchemy: v1.7.12
-->
<configurator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../zcl.xsd">
  <domain name="Measurement &amp; Sensing"/>
  <cluster>
    <domain>General</domain>
    <name>Soil Measurement</name>
    <code>0x0430</code>
    <define>SOIL_MEASUREMENT_CLUSTER</define>
    <description>This cluster provides an interface to soil measurement functionality, including configuration and provision of notifications of soil measurements.</description>
    <client init="false" tick="false">true</client>
    <server init="false" tick="false">true</server>
    <globalAttribute code="0xFFFD" side="either" value="1"/>
    <attribute code="0x0000" side="server" name="SoilMoistureMeasurementLimits" define="SOIL_MOISTURE_MEASUREMENT_LIMITS" type="MeasurementAccuracyStruct"/>
    <attribute code="0x0001" side="server" name="SoilMoistureMeasuredValue" define="SOIL_MOISTURE_MEASURED_VALUE" type="percent" isNullable="true"/>
  </cluster>
</configurator>
